"""model_file

Revision ID: 81ad6d41ac8e
Revises: 
Create Date: 2026-03-09 22:42:24.951171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ad6d41ac8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('playlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_songs_playlist_id', 'playlists', ['playlist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_songs_playlist_id', type_='foreignkey')
        batch_op.alter_column('playlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
