"""model_file

Revision ID: 8c85d1b8a653
Revises: 81ad6d41ac8e
Create Date: 2026-03-11 09:06:03.384556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c85d1b8a653'
down_revision: Union[str, Sequence[str], None] = '81ad6d41ac8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_songs_playlist_id'), type_='foreignkey')
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_songs_playlist_id'), 'playlists', ['playlist_id'], ['id'])

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=255), nullable=True),
    sa.Column('creater_id', sa.INTEGER(), nullable=True),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_comments_song_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
