"""model_file

Revision ID: c62f76d560dc
Revises: 8c85d1b8a653
Create Date: 2026-03-11 09:20:55.244697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62f76d560dc'
down_revision: Union[str, Sequence[str], None] = '8c85d1b8a653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=255), nullable=True),
    sa.Column('creater_id', sa.INTEGER(), nullable=True),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_comments_song_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
